server:
  servlet:
    context-path: /api
  port: 8082

spring:
  data:
    mongodb:
      database: jobsy-dev
      port: 27017
      host: localhost

jobsy:
  api:
    user-service:
      base-url: http://localhost:8080/api/v1/users
      create-endpoint: /create